[package]
name = "didyoumean"
authors = ["Hisbaan Noorani"]
version = "1.0.2-2"
edition = "2021"
license = "GPL-3.0"
description = "A cli spelling corrector"
documentation = "https://github.com/hisbaan/didyoumean"
homepage = "https://github.com/hisbaan/didyoumean"
repository = "https://github.com/hisbaan/didyoumean"
readme = "docs/README.md"
keywords = ["levenshtein", "damerau", "edit-distance"]
categories = ["command-line-utilities"]

[[bin]]
name = "dym"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
colored = { version = "2" }
cli-clipboard = {version = "0.2.1"}
# clipboard-ext = { version = "0.2.0" }
dialoguer = {version = "0.10.0"}

[target.'cfg(unix)'.dependencies]
nix = { version = "0.23.1" }
